# This cell is auto-generated.

In [97]:
data = 0
while data not in [1, 2]:
    data = int(input('Which data set do you want to use? 1 = Test, 2 = Input '))

if data == 1:
    fp = 'Test/'
    fn = '2208test.txt'
elif data == 2:
    fp = 'Input/'
    fn = '2208input.txt'

f = open(fp + fn, 'r')
raw = [j for j in f.read().splitlines()]

Which data set do you want to use? 1 = Test, 2 = Input 2


In [98]:
import numpy as np

In [99]:
raw = [[int(k) for k in j] for j in raw]
valGrid = np.array(raw)
valGrid

array([[3, 0, 0, ..., 2, 1, 1],
       [1, 3, 3, ..., 0, 3, 0],
       [2, 1, 3, ..., 1, 3, 3],
       ...,
       [3, 1, 0, ..., 1, 2, 1],
       [0, 1, 2, ..., 2, 3, 0],
       [3, 1, 1, ..., 0, 2, 2]])

In [100]:
vizGrid = np.ones(valGrid.shape, dtype='int')
vizGrid[1:-1, 1:-1] = 0
vizGrid

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 1],
       ...,
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [101]:
for r in range(1, valGrid.shape[0]-1):
    for c in range(1, valGrid.shape[1]-1):
        val = valGrid[r, c]
        up = valGrid[:r, c]
        dn = valGrid[r+1:, c]
        lf = valGrid[r, :c]
        rt = valGrid[r, c+1:]
#         print(val, [up, dn, rt, lf])
#         print((up<val).all(), (dn<val).all(), (rt<val).all(), (lf<val).all())
        if ((up<val).all() or (dn<val).all() or (rt<val).all() or (lf<val).all()):
            vizGrid[r, c] = 1

In [102]:
vizGrid

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 1, 1],
       [1, 0, 1, ..., 0, 0, 1],
       ...,
       [1, 0, 0, ..., 0, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [103]:
print('Part 1 Answer: ' + str(np.sum(vizGrid)))

Part 1 Answer: 1717


In [104]:
valGrid

array([[3, 0, 0, ..., 2, 1, 1],
       [1, 3, 3, ..., 0, 3, 0],
       [2, 1, 3, ..., 1, 3, 3],
       ...,
       [3, 1, 0, ..., 1, 2, 1],
       [0, 1, 2, ..., 2, 3, 0],
       [3, 1, 1, ..., 0, 2, 2]])

In [105]:
def chkArray(array, val):
    view = 0
    for i in array:
        if i < val:
            view += 1
        else:
            view += 1
            break
    return view

In [106]:
scenGrid = np.zeros(valGrid.shape, dtype='int')
for r in range(valGrid.shape[0]):
    for c in range(0, valGrid.shape[1]):
        val = valGrid[r, c]
        up = np.flip(valGrid[:r, c])
        dn = valGrid[r+1:, c]
        lf = np.flip(valGrid[r, :c])
        rt = valGrid[r, c+1:]
        upView = chkArray(up, val)
        dnView = chkArray(dn, val)
        lfView = chkArray(lf, val)
        rtView = chkArray(rt, val)
#         print(val, [up, dn, rt, lf], [upView, dnView, lfView, rtView])
        scenGrid[r, c] = upView * dnView * lfView * rtView
scenGrid

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  7,  6, ...,  1,  4,  0],
       [ 0,  1, 64, ...,  4, 18,  0],
       ...,
       [ 0,  2,  1, ...,  4,  6,  0],
       [ 0,  1,  8, ..., 12, 15,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [107]:
print('Part 2 Answer: ' + str(np.max(scenGrid)))

Part 2 Answer: 321975
